In [3]:
import pandas as pd
df = pd.read_csv('data.csv')

In [4]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,...,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,review_score,review_comment_message
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,3,voucher,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,4,"Não testei o produto ainda, mas ele veio corre..."
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2,voucher,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,4,"Não testei o produto ainda, mas ele veio corre..."
2,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,2017-08-15 18:29:31,2017-08-15 20:05:16,2017-08-17 15:28:33,2017-08-18 14:44:43,2017-08-28 00:00:00,1,credit_card,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,4,Deveriam embalar melhor o produto. A caixa vei...
3,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,2017-08-02 18:24:47,2017-08-02 18:43:15,2017-08-04 17:35:43,2017-08-07 18:30:01,2017-08-15 00:00:00,1,credit_card,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,5,"Só achei ela pequena pra seis xícaras ,mais é ..."
4,bfc39df4f36c3693ff3b63fcbea9e90a,53904ddbea91e1e92b2b3f1d09a7af86,delivered,2017-10-23 23:26:46,2017-10-25 02:14:11,2017-10-27 16:48:46,2017-11-07 18:04:59,2017-11-13 00:00:00,1,boleto,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,3,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 115608 entries, 0 to 115607
Data columns (total 33 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115608 non-null  str
 1   customer_id                    115608 non-null  str
 2   order_status                   115608 non-null  str
 3   order_purchase_timestamp       115608 non-null  str
 4   order_approved_at              115594 non-null  str
 5   order_delivered_carrier_date   114413 non-null  str
 6   order_delivered_customer_date  113208 non-null  str
 7   order_estimated_delivery_date  115608 non-null  str
 8   payment_sequential             115608 non-null  int64
 9   payment_type                   115608 non-null  str
 10  payment_installments           115608 non-null  int64
 11  payment_value                  115608 non-null  float64
 12  customer_unique_id             115608 non-null  str
 13  customer_zip_code_prefix       115608 non-null  int64
 14  customer_city                  115608 non-null  str
 15  customer_state                 115608 non-null  str
 16  order_item_id                  115608 non-null  int64
 17  product_id                     115608 non-null  str
 18  seller_id                      115608 non-null  str
 19  shipping_limit_date            115608 non-null  str
 20  price                          115608 non-null  float64
 21  freight_value                  115608 non-null  float64
 22  product_category_name          115608 non-null  str
 23  product_name_lenght            115608 non-null  float64
 24  product_description_lenght     115608 non-null  float64
 25  product_photos_qty             115608 non-null  float64
 26  product_weight_g               115607 non-null  float64
 27  product_length_cm              115607 non-null  float64
 28  product_height_cm              115607 non-null  float64
 29  product_width_cm               115607 non-null  float64
 30  product_category_name_english  115608 non-null  str
 31  review_score                   115608 non-null  int64
 32  review_comment_message         48905 non-null   str
dtypes: float64(10), int64(5), str(18)
memory usage: 29.1 MB

In [7]:
print(df.isnull().sum())

order_id                             0
customer_id                          0
order_status                         0
order_purchase_timestamp             0
order_approved_at                   14
order_delivered_carrier_date      1195
order_delivered_customer_date     2400
order_estimated_delivery_date        0
payment_sequential                   0
payment_type                         0
payment_installments                 0
payment_value                        0
customer_unique_id                   0
customer_zip_code_prefix             0
customer_city                        0
customer_state                       0
order_item_id                        0
product_id                           0
seller_id                            0
shipping_limit_date                  0
price                                0
freight_value                        0
product_category_name                0
product_name_lenght                  0
product_description_lenght           0
product_photos_qty                   0
product_weight_g                     1
product_length_cm                    1
product_height_cm                    1
product_width_cm                     1
product_category_name_english        0
review_score                         0
review_comment_message           66703
dtype: int64

In [8]:
df = df.drop(
                [
                    "order_approved_at",
                    "order_delivered_carrier_date",
                    "order_delivered_customer_date",
                    "order_estimated_delivery_date",
                    "order_purchase_timestamp",
                ],axis=1)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 115608 entries, 0 to 115607
Data columns (total 28 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115608 non-null  str
 1   customer_id                    115608 non-null  str
 2   order_status                   115608 non-null  str
 3   payment_sequential             115608 non-null  int64
 4   payment_type                   115608 non-null  str
 5   payment_installments           115608 non-null  int64
 6   payment_value                  115608 non-null  float64
 7   customer_unique_id             115608 non-null  str
 8   customer_zip_code_prefix       115608 non-null  int64
 9   customer_city                  115608 non-null  str
 10  customer_state                 115608 non-null  str
 11  order_item_id                  115608 non-null  int64
 12  product_id                     115608 non-null  str
 13  seller_id                      115608 non-null  str
 14  shipping_limit_date            115608 non-null  str
 15  price                          115608 non-null  float64
 16  freight_value                  115608 non-null  float64
 17  product_category_name          115608 non-null  str
 18  product_name_lenght            115608 non-null  float64
 19  product_description_lenght     115608 non-null  float64
 20  product_photos_qty             115608 non-null  float64
 21  product_weight_g               115607 non-null  float64
 22  product_length_cm              115607 non-null  float64
 23  product_height_cm              115607 non-null  float64
 24  product_width_cm               115607 non-null  float64
 25  product_category_name_english  115608 non-null  str
 26  review_score                   115608 non-null  int64
 27  review_comment_message         48905 non-null   str
dtypes: float64(10), int64(5), str(13)
memory usage: 24.7 MB

In [19]:
import numpy as np

# 1. Fill specific columns (Avoid inplace=True for better reliability)


# 1. Fill specific product dimensions with Median
cols_to_median = ["product_weight_g", "product_length_cm", "product_height_cm", "product_width_cm"]
for col in cols_to_median:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())

# 2. Handle the text column
if "review_comment_message" in df.columns:
    df["review_comment_message"] = df["review_comment_message"].fillna("No review")

# 3. Select Numeric Types ONLY
# This is crucial for Linear Regression
df = df.select_dtypes(include=[np.number])

# 4. THE SAFETY NET: Fill ANY remaining NaNs in numeric columns
# We use the median of the current numeric dataframe
df = df.fillna(df.median())

# 5. Drop non-predictive IDs
# FIX: Removed axis=1 because we are using the 'columns' parameter
cols_to_drop = ["customer_zip_code_prefix", "order_item_id"]
df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

# --- VERIFICATION STEPS (Great for Notebooks) ---
print(f"Final shape of data: {df.shape}")
print(f"Remaining NaN values: {df.isna().sum().sum()}")

# Show the first few rows to ensure it looks right
df.head()

Final shape of data: (115608, 13)
Remaining NaN values: 0

,payment_sequential,payment_installments,payment_value,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,review_score
0,3,1,2.00,29.99,8.72,40.0,268.0,4.0,500.0,19.0,8.0,13.0,4
1,2,1,18.59,29.99,8.72,40.0,268.0,4.0,500.0,19.0,8.0,13.0,4
2,1,3,37.77,29.99,7.78,40.0,268.0,4.0,500.0,19.0,8.0,13.0,4
3,1,1,37.77,29.99,7.78,40.0,268.0,4.0,500.0,19.0,8.0,13.0,5
4,1,1,44.09,29.99,14.10,40.0,268.0,4.0,500.0,19.0,8.0,13.0,3